apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: test-body
spec:
  version: "v2.0.0"
  image: "apisixtestaccount123/sample-go-func:v1"
  imageCredentials:
    name: push-secret
  port: 8080 # default to 8080
  serving:
    template:
      containers:
        - name: function # DO NOT change this
          imagePullPolicy: Never 
    runtime: "knative"
